const languageSettings = 
{
english: {    
    languageText: "ENGLISH",        
    textChoose: "Choose your language!",
    welcomeTextRed: "Work through JobFIXers",
    welcomeTextMore: "and earn more!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "I want to earn more!",
    buttonNextText: "Next",
    buttonTextJob: "I want a job!",
    firstNameText: "First name",
    lastNameText: "Name",
    telephoneNumberText: "Mobile phone",
    FNameErrorText: "First Name is not valid",
    LNameErrorText: "Last Name is not valid",
    TelephoneNumberError: "Phone number is not valid",
    EmptyErrorText: "All fields are required!",
    CheckBoxErrorText: "Check box is required!",
    workText: "I want to work as:",
    postalCodeText: "Postalcode",
    agreementText:"I agree to the",
    policyText: "JobFIXers privacy policy.",
    thankYouText: "Thanks!",
    thankYouTextOne: "We will call you as soon",
    thankYouTextTwo: "as possible",
    followText: "follow us on",
    industry: "Worker",
    construct: "Construction Worker",
    office: "Clerk"
},

dutch: {    
    languageText: "NEDERLANDS",
    welcomeTextRed: "Werk via JobFIXers",
    welcomeTextMore: "en verdien meer!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "Ik wil meer verdienen!",
    buttonNextText: "VOLGENDE",
    firstNameText: "Voornaam",
    lastNameText: "Naam",
    telephoneNumberText: "Mobiel",
    FNameErrorText: "Voornaam niet correct",
    LNameErrorText: "Naam niet correct",
    TelephoneNumberError: "Telefoonnummer niet correct",
    EmptyErrorText: "Alle velden zijn verplicht!",
    CheckBoxErrorText: "Selectievakje is verplicht!",
    workText: "Ik wil werken als",
    postalCodeText: "Postcode",
    agreementText: "Ik ga akkoord met de",
    policyText: "JobFIXers privacy policy.",
    buttonTextJob: "Ik wil een job!",
    thankYouText: "Bedankt!",
    thankYouTextOne: "We bellen jou zo snel",
    thankYouTextTwo: "als mogelijk op!",
    followText: "Volg ons op",
    industry: "Arbeider",
    construct: "Bouwvakker",
    office: "Bediende"
},

french: {    
    languageText: "FRANÇAIS",
    welcomeTextRed: "Travaillez via JobFIXers",
    welcomeTextMore: "et gagnez plus!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "Je veux gagner plus!",
    buttonNextText: "SUIVANTE",
    buttonTextJob: "Je veux un boulot!",
    firstNameText: "Prénom",
    lastNameText: "Nom",
    telephoneNumberText: "Mobile",
    FNameErrorText: "Erreur dans prénom",
    LNameErrorText: "Erreur dans nom",
    TelephoneNumberError: "Erreur dans numéro téléphone",
    EmptyErrorText: "Tous les champs sont obligatoires!",
    CheckBoxErrorText: "La case à cocher est obligatoire!",
    nextText: "Suivant",
    workText: "Je veux travailler comme",
    postalCodeText: "Code postal",
    agreementText: "Je suis d'accord avec la déclaration",
    policyText: "de confidentialité de JobFIXers.",
    thankYouText: "Merci! Nous vous appellerons dès que possible!",
    thankYouTextOne: "",
    thankYouTextTwo: "",
    followText: "Suivez nous",
    industry: "Travailleur",
    construct: "Travailleur de construction",
    office: "Employé"
}
};

export default languageSettings;